### ISSUE TITLE
Ability to rerun prepare steps during runtime

### ISSUE THREAD

**Issue by warflash** [johannschopplich/nuxt-prepare#11]
### Describe the feature

This might be completely out of scope for the project but ever since I saw your module, the idea of refreshing all or only certain prepare steps during runtime was quite enticing to me.

If your prepare step is done against a CMS or API, content might change and update during the apps runtime. With that I think it would be quite a lot faster and more intuitive to rerun the steps instead of rebuilding the entire app. Instead of restarting the entire build pipeline on CMS updates it simply calls a nitro webhook style which triggers prepare again.

Again, might be completely out of scope and I'm not even sure how doable it is to emit new js chunks during runtime and hook things up properly, so feel completely free to close the issue. Just wanted to get the idea out there😊

Thanks!

### Additional information

- [X] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-prepare/issues).

**Comment by johannschopplich** [comment]
While this is a great idea, it is not technically possible to emit a new JS chunk at runtime (without a build step). For runtime use, you're better off with a shared payload that is fetched from `useAsyncData` and stored globally somewhere in your application.

Down the road, the Nuxt team will be introducing [Nuxt build caching] (https://github.com/pi0/nuxt-build-cache), which could greatly reduce build times for your use case.

Thanks for the issue! 🙂

**Comment by johannschopplich** [comment]
@warflash Having slept a night over it, I think what you're looking for is something like [unstorage](https://unstorage.unjs.io/guide) + Cloudflare KV storage or something similar to store data between Nuxt instances at runtime.

**Comment by warflash** [comment]
Oh I didn't intend to make you loose sleep over this😊I appreciate the second thought and response tho!

Yes, unstorage + some sort of persistent storage does work indeed.
I was just not really satisfied with that solution and am looking for better ways.
- If the data is injected via useFetch/useAsyncData then you end up polluting the `__NUXT_DATA__` part of the sent html so nuxt can properly hydrate
- data pulled from the persistent store via fetch inherently will have less CDN and browser cacheability compared to a hashed js chunk

Like you said there is ways to solve the core problem. I just am not convinced yet they're the best in terms of performance - which is why I've been pondering about a solution similar to your module + runtime regeneration.

If I manage to catch daniels next stream maybe I can get some input from him whether the idea is completely impossible or whether there is a chance to make it work 😅

Again, appreciate the thought and response a ton!
