### ISSUE TITLE
Latest version crashes when running `prepare` script ('ERROR  File './.nuxt/tsconfig.json' not found.')

### ISSUE THREAD

**Issue by MuhammadM1998** [johannschopplich/nuxt-prepare#13]
### Environment

<details>
<summary><b>Stackblitz (Working)</b></summary>

- Operating System: Linux
- Node Version:     v18.18.0
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@8.15.6
- Builder:          -
- User Config:      modules, devtools
- Runtime Modules:  nuxt-prepare@2.0.0
- Build Modules:    -
</details>

<details>
<summary><b>Windows (Not Working)</b></summary>

- Operating System: Windows_NT
- Node Version:     v20.13.1
- Nuxt Version:     3.11.2
- CLI Version:      3.11.1
- Nitro Version:    2.9.6
- Package Manager:  pnpm@9.1.1
- Builder:          -
- User Config:      modules, devtools
- Runtime Modules:  nuxt-prepare@2.0.0
- Build Modules:    -
</details>

### Reproduction

https://stackblitz.com/edit/nuxt-starter-jd354j

### Describe the bug

I was bumping to v2 when the `prepare` command started failing with the following error.

```shell
ℹ Running prepare script server.prepare                                                                                                                   nuxt-prepare 11:25:29 pm

 ERROR  File './.nuxt/tsconfig.json' not found.                                                                                                                         11:25:29 pm

  at je (/C:/Users/Muhammad/Desktop/New%20folder/node_modules/.pnpm/get-tsconfig@4.7.5/node_modules/get-tsconfig/dist/index.mjs:7:6212)
  at ie (/C:/Users/Muhammad/Desktop/New%20folder/node_modules/.pnpm/get-tsconfig@4.7.5/node_modules/get-tsconfig/dist/index.mjs:7:7162)
  at le (/C:/Users/Muhammad/Desktop/New%20folder/node_modules/.pnpm/get-tsconfig@4.7.5/node_modules/get-tsconfig/dist/index.mjs:7:7877)
  at $e (/C:/Users/Muhammad/Desktop/New%20folder/node_modules/.pnpm/get-tsconfig@4.7.5/node_modules/get-tsconfig/dist/index.mjs:7:7982)
  at /C:/Users/Muhammad/Desktop/New%20folder/node_modules/.pnpm/tsx@4.10.5/node_modules/tsx/dist/esm/index.mjs?1716236729306:2:899
  at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
  at async ModuleLoader.import (node:internal/modules/esm/loader:316:24)
  at async Hooks.register (node:internal/modules/esm/hooks:165:26)
  at async MessagePort.handleMessage (node:internal/modules/esm/worker:196:18)
```

### Additional context

Steps to reproduce:
- Open the Stackblitz link and run `pnpm run postinstall` which runs the `prepare` command. Everything works fine
- Download the project (There's an icon above the sidebar) on a Windows machine and run `pnpm run postinstall`, it fails with the above error
- The error shows up in the CI too which is using Linux (same as Stackblitz) which is weird to me.

This is a screenshot of the error from my local machine 
![image](https://github.com/johannschopplich/nuxt-prepare/assets/86230182/f6005a81-c2ad-4abc-ad79-b5ca0bd76d2e)

**Comment by johannschopplich** [comment]
Thanks a lot for the bug report with reproductions! Seems to be an issue with a dependency, specifically `tsx`. I have reverted to use `jiti` for runtime TS support again.

I will publish a new version in the next minute.
