### ISSUE TITLE
[Feature]: Option to run specified `scripts` in parallel

### ISSUE THREAD

**Issue by muhammadmahmoud98** [johannschopplich/nuxt-prepare#16]
### Describe the feature

Hello!

From the following snippet, the module runs the passed `scripts` option one after the other.
https://github.com/johannschopplich/nuxt-prepare/blob/693b687a8a9a300ec4044131b566384f31e63e46/src/module.ts#L122-L176

Can we have a new option to run passed scripts in parallel to speed things up a bit? Maybe also add it to `PrepareScript` to allow granular opt-in for individual scripts. Currently I get around that by putting all my scripts in one file and wrap them with `Promise.all`

Thanks again for the great module 🙏

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-prepare/issues).

**Comment by johannschopplich** [comment]
Great idea! 👏

**Comment by muhammadmahmoud98** [comment]
That was fast! Thanks a lot 🙏
