### ISSUE TITLE
[Docs Request] Add example for how to use the module to fill the store

### ISSUE THREAD

**Issue by MuhammadM1998** [johannschopplich/nuxt-prepare#3]
### Describe the feature

Hello, 

Thanks for the great module. I've been looking for something like `NuxtServerInit` in Nuxt 2 to fill up my Pinia store on first run.

My use case is I scrape some data using playwright on the server and I need to run that at build time and fill that data into the store to then use it in the frontend (I'm serving the site as a SSG).

Afer searching and trying workarounds in [this discussion](https://github.com/vuejs/pinia/discussions/947) I managed to get it to work. But this package seems a much more cleaner way to do it. Can an example of usage with pinia be provided? I'm willing to help but I think I don't got the enough understanding for it sorry for that.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-prepare/issues).

**Comment by johannschopplich** [comment]
That is a valid point!
 
I have implemented a new feature with [v0.2.0](https://github.com/johannschopplich/nuxt-prepare/releases/tag/v0.2.0) – is this what you are looking for?

Updated docs 👉  https://nuxt-prepare.byjohann.dev/guide/example-pass-state-to-nuxt.html

**Comment by johannschopplich** [comment]
I've been itching to try and figure out how to help you. You're welcome! If you run into any errors, feel free to open a separate issue.
