### ISSUE TITLE
Autodetect pinia

### ISSUE THREAD

**Issue by mrleblanc101** [johannschopplich/nuxt-prepare#4]
### Describe the feature

Hey,
If pinia is installed, it would be nice to call a `nuxtServerInit` and `nuxtClientInit` pinia action like Nuxt 2 did with VueX.

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-prepare/issues).

**Comment by johannschopplich** [comment]
Great idea!

**Comment by johannschopplich** [comment]
What should be the intention of `nuxtClientInit`? What shall it do? Pinia hydrates the server payload so I'm unsure what you expect from `nuxtClientInit`.

**Comment by johannschopplich** [comment]
I must admit, I don't quite get, how Nuxt Prepare should detect which Pinia Store you use and where to inject a custom action. 

For client-side action, you can just use `import.meta.client` which is provided by Nuxt as a build flag to target the browser build.

If you have a specific use-case, please provide a descriptive and reproducible example in a separate issue. Thanks!

Closing this, as the [docs example for Pinia](https://nuxt-prepare.byjohann.dev/guide/example-pass-state-to-nuxt.html) basically covers this use-case.

**Comment by mrleblanc101** [comment]
I think it should auro-detect the root store. `stores/index.js`

**Comment by johannschopplich** [comment]
That's up to the developer, if he uses a root store or now. I don't like the approach of guessing a "default" store.
