### ISSUE TITLE
Use with ?preview=true

### ISSUE THREAD

**Issue by wirsindplural** [johannschopplich/nuxt-prepare#5]
### Describe the feature

Hi @johannschopplich, 
I love and regularly use nuxt-prepare. But sometimes it'd be handy to have the chance to update data in preview mode (preview=true). Is there any chance to implement this myself? Or could this be an upcoming feature?

Thanks for your thoughts on this topic!
Tobi

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-prepare/issues).

**Comment by johannschopplich** [comment]
Hi @wirsindplural!

Thanks for the flowers. Glad to hear you enjoy the plugin.

I don't understand what you mean by `?preview=true` – a query parameter? Since Nuxt Prepare will run before Nuxt builds its server, it has no access to the server instance, query parameters respectively.

If you want to use some kind of local flag for different prepared data, you can use an environment variable. Example:

```json
  "scripts": {
    "dev": "PREVIEW=true nuxi de",
  },
```

In your prepare script you can then do different actions based on the flag:

```ts
export default defineNuxtPrepareHandler(async () => {
  let items = []

  if (process.env.PREVIEW) {
    items.push("preview is enabled")
  }

  return {
    state: {
      items
    }
  }
})
```

Does this solve your problem?

**Comment by wirsindplural** [comment]
Hey, please excuse my misleadingly worded question. 

What I'd like to do is having a Preview-Link in my CMS for my clients to see their changes without having to trigger a full build of the site. I was thinking that nuxt3 has the same preview feature as nuxt2 (https://v2.nuxt.com/docs/features/live-preview/). 

What I'm trying to do now is to use a plugin to hook into page:finish and fetch all data again from there (only when preview=true is set). I'm not really sure how to properly abstract my prepare/ store logic to be able to do this but if I'm successful, I'll let you know!

Best, 
Tobi

`export default defineNuxtPlugin((nuxtApp) => {
	const route = useRoute();
	const preview = route.query.preview && route.query.preview === 'true';

	if (preview) {
    nuxtApp.hook('page:finish', () => {
      // refresh data
		});
	}

	return { provide: { preview } };
});`

**Comment by johannschopplich** [comment]
I see. That's a different feature than what Nuxt Prepare tries to solve. But you can combine it with Nuxt Prepare! When you have preloaded data, you can use it conditionally:

```ts
import { todos } from '#nuxt-prepare'

const route = useRoute()
const data = useAsyncData(() => {
  if (route.query.preview) return todos

  return $fetch('/api/todos')
})
```

Sure, feel free to post your solution here for other users stumbling over this issue. I consider this issue to be resolved and will close it. 🙂
