### ISSUE TITLE
Can I set runtime config with the result of a prepare script?

### ISSUE THREAD

**Issue by MuhammadM1998** [johannschopplich/nuxt-prepare#6]
### Describe the feature

Not really a feature but didn't find a 'Question' button 😅

We were reading a runtime config key from env variable and now we fetch it from an API using the module at build time.
Is there a way we can set that runtime config key with the result we get from the API? Currently we store it in a `useState` and it works well but saving it to runtime config would be more clean. Thanks!

I think this is similar to https://github.com/nuxt/nuxt/issues/15366

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-prepare/issues).

**Comment by johannschopplich** [comment]
Oh, shoot, you're right, I have to enable GitHub Discussions!

Yes, you overwrite runtime config variables:

```ts
// `server.prepare.ts`
import { defineNuxtPrepareHandler } from 'nuxt-prepare/config'

export default defineNuxtPrepareHandler(async () => {
  // Do some async magic here, e.g. fetch data from an API

  return {
    // If not set, defaults to `true`
    ok: true,

    // Overwrite the runtime config variable `foo`
    runtimeConfig: {
      public: {
        foo: 'Overwritten by "server.prepare" script'
      }
    }
  }
})
```

**Comment by MuhammadM1998** [comment]
lol I didn't thought it would be this easy! Thanks a lot!

Sidenote: I think a 'Question' option would be better than Discussions for the module's scope. No need for another whole tab imo. Thanks again 🙏
