### ISSUE TITLE
Clarify what the modules actually does in the docs

### ISSUE THREAD

**Issue by maximilliangeorge** [johannschopplich/nuxt-prepare#8]
### Describe the feature

I would like to clearly understand from the docs what this module can help me with. I think it might be useful for an issue I'm facing, but I'm honestly not sure if I'm just projecting my needs onto this module. A simple paragraph explaining the limitations of Nuxt and what issue this module aims to solve would help me better grasp whether I should use this module or not.

Cheers!

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-prepare/issues).

**Comment by johannschopplich** [comment]
Valid point. 👍

**Comment by johannschopplich** [comment]
Fixed in https://github.com/johannschopplich/nuxt-prepare/commit/d5a52071c469e561469953900b0e697eda3bb7a5.
