### ISSUE TITLE
Nuxt prepare scripts for specific route

### ISSUE THREAD

**Issue by adrian-cytrix** [johannschopplich/nuxt-prepare#9]
### Describe the feature

i could to ask if its possible to specific prepare handler for specific route like
prepare for foo route
prepare for bar route

than calling all api on single handler

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Can you think of other implementations of this feature?

### Final checks

- [X] Check existing [issues](https://github.com/johannschopplich/nuxt-prepare/issues).

**Comment by johannschopplich** [comment]
I think this is a misunderstanding of the module. The module will run scripts _before_ Nuxt itself is built. That is, before any of the routes are run.

I don't know what your use case is, but an internal API call might be the better choice here.

However, you can just preload all of your important data and import it in your routes as needed:

```ts
// pages/foo.vue
import { fooData } from '#nuxt-prepare'

// pages/bar.vue
import { barData } from '#nuxt-prepare'
```

**Comment by adrian-cytrix** [comment]
```
// `store.prepare.ts`
import { $fetch } from 'ofetch'
import type { FetchError } from 'ofetch'
import { defineNuxtPrepareHandler } from 'nuxt-prepare/config'

export default defineNuxtPrepareHandler(async () => {
  let todos: Record<string, unknown> | undefined;
  let users: Record<string, unknown> | undefined
  let error: FetchError | undefined

  try {
    todos = await $fetch('todos/1', {
      baseURL: 'https://jsonplaceholder.typicode.com',
    });
    users = await $fetch('users', {
      baseURL: 'https://jsonplaceholder.typicode.com',
    })
  }
  catch (err) {
    error = err as FetchError
    console.error(error)
  }

  return {
    // If the fetch failed, we want to halt the build
    ok: !error,

    // Pass your todos data to Nuxt and import it
    // anywhere from `#nuxt-prepare`
    state: {
      todos,
      users,
    },
  }
```
i think it will preload all the data even the route is not calling due to inherit feature you have.
